// AUTO-GENERATED by build-categories-meta.ts — do not edit
// Generated: 2026-02-02T09:54:58.544Z

import type { CategoryMeta } from '@/next-blog/types/blog';

export const categoriesMeta: CategoryMeta[] = [
  {
    "slug": "the_white_witch",
    "title": "️Witchy Blog✨",
    "description": "My blog where I share what is on my mind, and what I am working on.",
    "date": "2026-02-01",
    "path": "/blog/the_white_witch",
    "emoji": "🧙‍♀",
    "pinned": true,
    "featured": true,
    "tags": [],
    "posts": 2,
    "latest": "2026-02-01"
  },
  {
    "slug": "epstein_files",
    "title": "️Epstein Files!",
    "description": "My view on the Epstein Files, and thee Trump admin trying to hide them!",
    "date": "2026-02-02",
    "path": "/blog/epstein_files",
    "emoji": "💩",
    "pinned": false,
    "featured": true,
    "tags": [],
    "posts": 1,
    "latest": "2026-02-02"
  },
  {
    "slug": "mental_insane",
    "title": "️This is mental, this is insane!",
    "description": "May the flying spaghetti monster have mercy on our souls!",
    "date": "2026-02-02",
    "path": "/blog/mental_insane",
    "emoji": "🍝",
    "pinned": false,
    "featured": true,
    "tags": [],
    "posts": 0,
    "latest": "1900-01-01"
  },
  {
    "slug": "today_in_history",
    "title": "️Today in History",
    "description": "Doom Edition. Covering the worst events of that day in history!",
    "date": "2026-02-02",
    "path": "/blog/today_in_history",
    "emoji": "🤹🏼‍♀️",
    "pinned": false,
    "featured": false,
    "tags": [],
    "posts": 0,
    "latest": "1900-01-01"
  }
];
