// AUTO-GENERATED by build-categories-meta.ts — do not edit
// Generated: 2026-02-03T08:37:52.175Z

import type { CategoryMeta } from '@/next-blog/types/blog';

export const categoriesMeta: CategoryMeta[] = [
  {
    "slug": "people",
    "title": "️Today in History",
    "description": "Doom Edition. Covering the worst events of that day in history!",
    "date": "2026-02-03",
    "path": "/blog/people",
    "emoji": "🤹🏼‍♀️",
    "pinned": false,
    "featured": false,
    "tags": [],
    "posts": 0,
    "latest": "1900-01-01"
  },
  {
    "slug": "sites",
    "title": "️Today in History",
    "description": "Doom Edition. Covering the worst events of that day in history!",
    "date": "2026-02-03",
    "path": "/blog/sites",
    "emoji": "🤹🏼‍♀️",
    "pinned": false,
    "featured": false,
    "tags": [],
    "posts": 0,
    "latest": "1900-01-01"
  }
];
