// AUTO-GENERATED by build-posts-meta.ts — do not edit
// Generated: 2026-02-02T09:55:01.638Z

import type { PostMeta } from '@/next-blog/types/blog';

export const postsMeta: PostMeta[] = [
  {
    "slug": "epstein_files/introduction",
    "title": "Epstein Files: Trump's Tangled Tango with the Pedo Prince",
    "description": "Intro to the shady saga where Trump promised transparency but delivered drama. Witchy vibes on guilt and gaffes.",
    "date": "2026-02-02",
    "path": "/blog/epstein_files/introduction",
    "category": "epstein_files",
    "emoji": "📝",
    "pinned": false,
    "featured": false,
    "expanded": false,
    "tags": [],
    "excerpt": "h4>Trump&#39;s Epstein Entanglement: A Guilty Glow-Up?</h4>\n<p>Oh, darlings, gather &#39;round my cauldron for this steaming brew of bullshit. Back in the &#39;90s, Trump and Epstein were thicker than thieves at Mar-a-Lago—flying on Lolita Express, Trump gushing in 2002: &quot;Terrific guy, likes &#39;em young....",
    "long": true
  },
  {
    "slug": "the_white_witch/About-Me",
    "title": "About Me",
    "description": "### 🧙‍♀️ About The White Witch™ ✨\r\n\r\nBorn in the 70s, somehow still looking like I’m perpetually stuck in my 30s. Good genes, better skincare, or just spite—ta…",
    "date": "2026-02-01",
    "path": "/blog/the_white_witch/About-Me",
    "category": "the_white_witch",
    "emoji": "📝",
    "pinned": false,
    "featured": false,
    "expanded": false,
    "tags": [],
    "excerpt": "About The White Witch™ ✨</h3>\n<p>Born in the 70s, somehow still looking like I’m perpetually stuck in my 30s. Good genes, better skincare, or just spite—take your pick.</p>\n<p>PhD in Computer Science, MSc in Economics. Yes, both. I like collecting expensive pieces of paper that prove I can overthink for a living....",
    "long": true
  },
  {
    "slug": "the_white_witch/Introduction",
    "title": "Introduction",
    "description": "### 🧙‍♀️Hi!, Welcome! ✨\r\n#### Here is an about me, in short form:\r\n🪪Citizenship: 🇪🇺 🇩🇪 🇺🇸<br/>\r\n🗺️Location: 🇪🇺 🇩🇪<br/>\r\n⛪Religion: Pagan/Agnostic<b…",
    "date": "2026-02-01",
    "path": "/blog/the_white_witch/Introduction",
    "category": "the_white_witch",
    "emoji": "📝",
    "pinned": false,
    "featured": false,
    "expanded": false,
    "tags": [],
    "excerpt": "i!, Welcome! ✨</h3>\n<h4>Here is an about me, in short form:</h4>\n<p>🪪Citizenship: 🇪🇺 🇩🇪 🇺🇸<br/>\n🗺️Location: 🇪🇺 🇩🇪<br/>\n⛪Religion: Pagan/Agnostic<br/>\n🏫Background: Technology, Economics, History<br/>\n👀Views: Centrist, Common Sense🦄<br/>\n👍🏼Likes: Music, Culture, Facts, Debates<br/>\n👎🏼Dislikes: Tyranny,  Propaganda<br/>\n📙Content: Questionable Humor and Sarcasm🤣<br/></p>\n<h4>👉Follow Me💖</h4>\n<p>I am the @thewhitewitchtm on:<br/>...",
    "long": true
  }
];
